name: Bssentials
version: 3.0-pre
authors: [IsaiahPatton, Bssentials Contributors]
main: bssentials.Bssentials
description: Essentials remake with support for EssAPI
website: http://dev.bukkit.org/bukkit-plugins/bssentials/