name: Bssentials
version: ${full.version}
authors: [Isaiah, ramidzkh, krisp, Machine-Maker]
main: bssentials.bukkit.BssentialsPlugin
description: Essentials features for Bukkit/Spigot. Remake of EssentialsX
softdepend: [Vault]
