name: Essentials
main: com.earth2me.essentials.Essentials
version: 2.0.1-Bssentials
description: Bridges the Essentials API to work with Bssentials.
softdepend: [Vault]
authors: [Bssentials Contributers]