# The Bssentials 2 config!

#Enable the update check?
checkForUpdate: true

#Ranks
ranks:
    #the format is the way the chat will look!
    # %rank% is the players rank!
    # the 1st %s is the players name
    # the 2nt %S is the chat message
    format: "%rank% %s : %s"
    #the Enable is if you don't what to have the built-in ranks you can set it to false
    enable: true
    #Here are example ranks!
    default:
        prefix: "&7[Default]&f"
    owner:
        prefix "&4[Owner]&c"
        
    

#Here is player's data, ex: nicknames and ranks!
playerdata:

#Warps!!
#Now stored in warps.yml