# The Bssentials main configuration
# DO NOT CHANGE CONFIG VERSION BELOW
configVersion: 1

# enable the update check?
checkForUpdate: true

# Your server's Staff members
staff:
  - 'This is the staff command!'
  - 'Edit this in your Bssentials config.yml'

# Disable any command on your server
commandBlackList:
    - 'cmd1'
    - 'cmd2'